train:
  train_name: TD3-train # Task name
  device: cuda:0 # Device
  qf_lr: 0.00001 # Learning rate for Q function
  ac_lr: 0.00001 # Learning rate for actor
  exploration_noise: 0.1
  policy_noise: 0.05
  noise_clip: 0.1
  gamma: 0.995
  tau: 0.005

  total_timesteps: 3000000
  learning_starts: 1000
  batch_size: 512
  save_interval: 1000
  policy_freq: 2

  buffer:
    size: 5000000


  env: 
    task: Anymal # Environment name
    num_envs: 4096 # Number of environments
    seed: 0 # Random seed
    sim_device: cuda:0
    rl_device: cuda:0
    graphics_device_id: 0
    headless: False
    multi_gpu: False
    force_render: True
  network:
    hidden_dim: 128