train:
  train_name: CartPole # Task name
  device: cuda:0 # Device
  lr: 0.0001 # Learning rate
  gamma: 0.99 # Discount factor
  gae_lambda: 0.95 # GAE lambda
  clip: 0.2 # PPO clip
  ent_coef: 0.0 # Entropy coefficient
  vf_coef: 2 # Value function coefficient
  max_grad_norm: 1 # Max gradient norm
  vloss_clip: True
  vloss_clip_coef: 0.2

  num_steps: 16
  total_timesteps: 5000000
  batch_size: 128
  update_epochs: 4
  minibatch_size: 32

  env: 
    task: Cartpole # Environment name
    num_envs: 4096 # Number of environments
    seed: 0 # Random seed
    sim_device: cuda:0
    rl_device: cuda:0
    graphics_device_id: 0
    headless: False
    multi_gpu: False
    force_render: True
  network:
    hidden_dim: 128