train:
  train_name: TD3-train # Task name
  device: cuda:0 # Device
  qf_lr: 0.0003 # Learning rate for Q function
  ac_lr: 0.0003 # Learning rate for actor
  gamma: 0.99
  tau: 0.005

  total_timesteps: 3000000
  batch_size: 512
  save_interval: 1000
  policy_freq: 2
  target_freq: 2

  alpha: 0.2
  auto_entropy: True

  buffer:
    size: 10000000

  env: 
    task: Anymal # Environment name
    num_envs: 1024 # Number of environments
    seed: 0 # Random seed
    sim_device: cuda:0
    rl_device: cuda:0
    graphics_device_id: 0
    headless: False
    multi_gpu: False
    force_render: True
  network:
    hidden_dim: 128